var colors = generateRandomColors(6);


// var colors = [
   
// ];
var pickedColor = randomColor();
var squares = document.querySelectorAll('.square');
var displayColor = document.querySelector('#display');
var message = document.getElementById('message');
var h1 = document.querySelector('h1');
var reset = document.querySelector('#new');

// helper function that selects random color from colors array
function randomColor() {
    var ran = Math.floor(Math.random() * colors.length);
    return colors[ran];
}

/* function captures random color generated by pickedColor function and assigns it to pickedColor variable and displays that value in the #display span */
function pickedColorDisplay() {
    // pickedColor = randomColor();
    displayColor.textContent = pickedColor;   
}

// helper function that generates and returns a random rgb color
function makeColor() {
    var r = Math.floor(Math.random() * 256);
    var g = Math.floor(Math.random() * 256);
    var b = Math.floor(Math.random() * 256);
    return `rgb(${r}, ${g}, ${b})`;
}

// function that generates a an array of random rgb colors
function generateRandomColors(num) {
    // make array
    var arr = [];

    // add number of random colors to array
    for (var i = 0; i < num; i++) {
        arr.push(makeColor());
    }

    // return array
    return arr;

}

/* helper function that changes the background color of all the squares and the background color of the h1 element to match the pickedColor variable */
function changeColors() {
    for (var i = 0; squares.length; i++) {
        squares[i].style.backgroundColor = pickedColor;
        h1.style.backgroundColor = pickedColor;
    }
}


function squareRandom() {
    
    for (var i = 0; squares.length; i++) {
        squares[i].style.backgroundColor = colors[i];
        h1.style.backgroundColor = '#232323';

        squares[i].addEventListener('click', function () {
            if (this.style.backgroundColor === pickedColor) {
                message.textContent = "CORRECT!!!";
                changeColors();
            } else {
                this.style.backgroundColor = '#232323';
                message.textContent = "TRY AGAIN!!!";
            }
        });
    }
}


function newGame () {
    reset.addEventListener('click', function() {
        colors = generateRandomColors(6);
        pickedColor = randomColor();
        pickedColorDisplay();
        squareRandom();
    });
}

pickedColorDisplay();
newGame();
squareRandom();
